### ISSUE TITLE
[Save/Load State] Slash & Dust button not captured by save/load inputs

### ISSUE THREAD

**Issue by Ninetime** [adanducci/GGPOPLUSR#34]
**Describe the bug**
None of the buttons within the save/load tool are currently mapped to the slash button. The current outputs are:
P: K
K: H
S: P
H: PKHS
D: Respect
P1 Respect: PKS
P2 Respect: D

**To Reproduce**
1. Open Save/Load state tool
2. Attempt to use any of the current mapped buttons
3. Output will not show Slash exclusively

**Expected behavior**
The slash & dust button should map to slash & dust respectively

**Screenshots or video capture**
If applicable, add screenshots or a video capture to help explain your problem.
![image](https://user-images.githubusercontent.com/6248582/72780598-37f03b00-3bed-11ea-8320-67d28967f604.png)
![image](https://user-images.githubusercontent.com/6248582/72780791-c06edb80-3bed-11ea-9d4a-29d41d3bbc72.png)
![image](https://user-images.githubusercontent.com/6248582/72780819-d086bb00-3bed-11ea-845e-d23ac026b4f4.png)
![image](https://user-images.githubusercontent.com/6248582/72780834-d7153280-3bed-11ea-95ae-9d9e7b024ef2.png)

**Desktop (please complete the following information):**
 - All total connected controllers  XInput device, keyboard
 - Mode Training
 - Selected characters P1 Sol vs. P2 Ky
 - Active controller per player P1 was using an XInput device, and P2 was using the keyboard

**Additional context**

**Comment by Ninetime** [comment]
Updated with info that P2 respect produces Dust while P1 produces 3 hits

**Comment by adanducci** [comment]
Closed by #35 .
