### ISSUE TITLE
[LAUNCHER] Error codes when launching tool on new machine

### ISSUE THREAD

**Issue by Ninetime** [adanducci/GGPOPLUSR#43]
**Describe the bug**
Attempting to open launcher.exe shows errors

**To Reproduce**
1. Install GGPOPLUSR-0.0.0-win32.exe
2. Open Launcher.exe

**Expected behavior**
The program should launch successfully.

**Screenshots or video capture**
![image (1)](https://user-images.githubusercontent.com/6248582/74301875-7c6d8300-4d22-11ea-92d7-9175fdeaa10a.png)
![image (2)](https://user-images.githubusercontent.com/6248582/74301878-7d9eb000-4d22-11ea-8899-47a3ae1ea984.png)
![image (3)](https://user-images.githubusercontent.com/6248582/74301881-80010a00-4d22-11ea-9efd-d38a5db19257.png)

**Desktop (please complete the following information):**
 - Do you have a `steam_appid.txt` file in your application folder? [Yes]
 - OS: [Win 10]
 - Antivirus: [Windows Defender]
 - GGPOPLUSR tool version: 0.0.0
 - System display resolution: 1080x720
 - Guilty Gear display resolution: 1920x1080
 - Guilty Gear display type (ex. windowed)

**Additional context**

**Comment by FIXMESTEVE** [comment]
Latest commit of [FIXMESTEVE:feature/installer/getGgxxacprDirFromRegAndMoveGgpoDllThere](https://github.com/FIXMESTEVE/GGPOPLUSR/tree/feature/installer/getGgxxacprDirFromRegAndMoveGgpoDllThere) should fix this bug.

**Comment by FIXMESTEVE** [comment]
There was some feedback on Discord these past days about this problem being resolved so I'll tentatively close the issue
Fixed by https://github.com/adanducci/GGPOPLUSR/pull/45
